const data = {
    photos: [  
        {
            id: "1",
            src: "../img/img1.jpg",
            credit: "Bernice McElligott",
            title: "Crash",
            alt: "A crashing tidal wave",
        },
        {
            id: "2",
            src: "../img/img2.jpg",
            credit: "Tatyana Vacek",
            title: "Perfect Glass",
            alt: "An ebony woman contrasted on white",
        },
        {
            id: "3",
            src: "../img/img3.jpg",
            credit: "Woodie Fabron",
            title: "LOOK AT HIM",
            alt: "An adorable dog",
        },
        {
            id: "4",
            src: "../img/img4.jpg",
            credit: "Vlatko Horton",
            title: "tribute",
            alt: "Graffiti of Biggie Smalls",
        },
        {
            id: "5",
            src: "../img/img5.jpg",
            credit: "Yulia Byrne",
            title: "SPORTS",
            alt: "A hockey player dunking a basketball",
        },
        {
            id: "6",
            src: "../img/img6.jpg",
            credit: "Deepti Stone",
            title: "Us Too",
            alt: "A Homeless man holding up a sign that reads Seeking Human Kindness",
        },
        {
            id: "7",
            src: "../img/img7.jpg",
            credit: "Quincey Metaxas",
            title: "Let Go",
            alt: "A couple sitting together in a field",
        },
        {
            id: "8",
            src: "../img/img8.jpg",
            credit: "Paul Powell",
            title: "I AM",
            alt: "A female lion roaring",
        },
        {
            id: "9",
            src: "../img/img9.jpg",
            credit: "Gideon Maina",
            title: "ITS A GIRL",
            alt: "A gender reveal announcing the birth of a girl",
        },
        {
            id: "10",
            src: "../img/img10.jpg",
            credit: "Beatrix Walsh",
            title: "aaraam karen",
            alt: "A Hindu man smoking and relaxing",
        },
        {
            id: "11",
            src: "../img/img11.jpg",
            credit: "Koba Labelle",
            title: "Leave me alone",
            alt: "A row of trees creating path",
        },
        {
            id: "12",
            src: "../img/img12.jpg",
            credit: "Leonard Switzer",
            title: "Make It Official",
            alt: "A couple getting married",
        },
    ],
}

export default data;